<?php
/**
 * Template Name: Radio Page
 *
 * Template for pages
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

get_header(); ?>

	<div id="content-full" class="content-area">
		<main id="main" class="site-main full-width" role="main">

			<?php if ( have_posts() ) : ?>

				<?php get_template_part( 'template-parts/loop-header' ); ?>

				<?php /* Start the Loop */ ?>
				<?php while ( have_posts() ) : the_post(); ?>

					<?php get_template_part( 'template-parts/content', 'page' ); ?>

				<?php endwhile; ?>

				<?php



$bmplayer_playlist=array();

// WP_Query arguments
$query_args = array (
	'post_type'              => 'bmplayer_track',
	'post_status'            => 'publish',
	'nopagging'    => true,
	'posts_per_page'   =>  '-1',
	'meta_query'             => array(
		array(
			'key'      => 'bmplayer_track_url',
		)
	)
);

$args['order']=$args['order']?$args['order']:'ASC';
		if($args['order']=='rand'){
			$query_args['orderby']='rand';
		}else{
			$query_args['order']=$args['order'];
			$query_args['orderby']='menu_order';			
		}


// The Query
$tracks_query = new WP_Query( $query_args );

// The Loop
if ( $tracks_query->have_posts() ) {
	while ( $tracks_query->have_posts() ) {
		$tracks_query->the_post();
		$post_id=get_the_ID();
		$track_url=get_post_meta( $post_id, 'bmplayer_track_url', true );
		$track_title=get_the_title();
		$track_artist='undefined';
		//array_push( $bmplayer_playlist, array( 'id'=>$post_id, 'title'=>$track_title ) );
		$bmplayer_playlist[] = array( 'id'=>$post_id, 'title'=>$track_title ) ;
	}
} else {
	// no posts found
}

// Restore original Post Data
wp_reset_postdata();


//Start table

echo '<table id="RadioElements">';

echo "<th><h3>Title</h3></th>";
// Loop through database



for ($rows=0; $rows < sizeof($bmplayer_playlist); $rows++) { 
	?>
	<tr><td id="<?php echo $bmplayer_playlist[$rows][title]; ?>"  class="clickable" data-href="<?php echo $rows?>">
	<h4><?php	echo $bmplayer_playlist[$rows][title]; ?> </h4>
	</td></tr>
<?php
}
echo "</table>";

?>

			<?php else : ?>

				<?php get_template_part( 'template-parts/content', 'none' ); ?>

			<?php endif; ?>

		</main><!-- #main -->
	</div><!-- #content-full -->

<?php get_footer(); ?>

<script type="text/javascript">
jQuery(document).ready(function($) {

	var playing = Cookies.get("Playing");
    $(".clickable").click(function() {
    var chosenTrackID = $(this).data("href");
	Cookies.set("TrackID", chosenTrackID, { expires: 7 }, { path: '/' });
	
	if(!(typeof(playing) != "undefined" && playing !== null) || playing==="0") {
		Cookies.set("Playing", 1, { expires: 1 }, { path: '/' });
 	}

	location.reload();

    });
});
</script>
